# Generated by Django 3.0.3 on 2020-03-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manager',
        ),
    ]
