# Generated by Django 3.0.3 on 2020-03-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_tasklist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manager',
            new_name='manage',
        ),
    ]
